---
brew_packages:
  - autojump # jump any recent folder
  - awscli # manage amazon web service on cli
  - bat # replace cat
  - curl
  - direnv # env var for shell
  - exa # replace ls
  - fd # replace grep
  - fish # replace zsh
  - fzf # replace grep
  - git
  - go
  - htop # interactive process viewer
  - mas # mac app store cli
  - neofetch # system information
  - node
  - python
  - thefuck # corrects previous console command
  - tmux # multiple terminal session
  - tree # show directory tree
  - youtube-dl # download youtube media
  - yarn

brew_taps:
  - homebrew/cask-fonts

brew_apps:
  - 1password
  - alfred
  - alt-tab
  - clion
  - cloudflare-warp
  - datagrip
  - discord
  - docker
  - evernote
  - font-inconsolata
  - goland
  - google-chrome
  - istat-menus
  - iterm2
  - jetbrains-toolbox
  - messenger
  - openkey
  - phpstorm
  - postman
  - pycharm
  - rectangle
  - skype
  - slack
  - telegram-desktop
  - transmission
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - webstorm
  - zalo

mas_apps: [
  { id: 540348655, name: "Monosnap" },
]

post_install:
  defaults: [
    # Mouse
    { domain: "com.apple", key: "swipescrolldirection", type: "bool", value: "NO" },
    # Dock
    { domain: "com.apple.dock", key: "autohide", type: "bool", value: "true" },
    { domain: "com.apple.dock", key: "magnification", type: "bool", value: "true" },
    { domain: "com.apple.dock", key: "orientation", type: "string", value: "left" },
    { domain: "com.apple.dock", key: "largesize", type: "float", value: "85" },
    { domain: "com.apple.dock", key: "tilesize", type: "float", value: "45" },
    { domain: "com.apple.dock", key: "show-recents", type: "bool", value: "false" },
    { domain: "com.apple.dock", key: "mineffect", type: "string", value: "suck" },
    { domain: "com.apple.dock", key: "minimize-to-application", type: "bool", value: "true" },
    { domain: "com.apple.dock", key: "wvous-br-corner", type: "int", value: "5" },
    { domain: "com.apple.dock", key: "wvous-br-modifier", type: "int", value: "0" },
    { domain: "com.apple.dock", key: "static-only", type: "bool", value: "true" },
    #    { domain: "com.apple.dock", key: "autohide-delay", type: "float", value: "0" },
    #    { domain: "com.apple.dock", key: "autohide-time-modifier", type: "float", value: "0" },
    # Finder
    { domain: "com.apple.finder", key: "QuitMenuItem", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "NewWindowTarget", type: "string", value: "PfLo" },
    { domain: "com.apple.finder", key: "NewWindowTargetPath", type: "string", value: "file://${HOME}/Downloads" },
    { domain: "com.apple.finder", key: "ShowExternalHardDrivesOnDesktop", type: "bool", value: "false" },
    { domain: "com.apple.finder", key: "ShowHardDrivesOnDesktop", type: "bool", value: "false" },
    { domain: "com.apple.finder", key: "ShowRemovableMediaOnDesktop", type: "bool", value: "false" },
    { domain: "com.apple.finder", key: "AppleShowAllFiles", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "AppleShowAllExtensions", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "ShowStatusBar", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "PathBarRootAtHome", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "ShowPathbar", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "ShowPreviewPane", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "QLEnableTextSelection", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "_FXShowPosixPathInTitle", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "FXDefaultSearchScope", type: "string", value: "SCcf" },
    { domain: "com.apple.finder", key: "FXEnableExtensionChangeWarning", type: "bool", value: "false" },
    { domain: "com.apple.finder", key: "FXPreferredViewStyle", type: "string", value: "Nlsv" },
    { domain: "com.apple.finder", key: "SearchRecentsSavedViewStyle", type: "string", value: "Nlsv" },
    { domain: "com.apple.finder", key: "WarnOnEmptyTrash", type: "bool", value: "false" },
    { domain: "com.apple.finder", key: "EmptyTrashSecurely", type: "bool", value: "true" },
    { domain: "com.apple.frameworks.diskimages", key: "auto-open-ro-root", type: "bool", value: "true" },
    { domain: "com.apple.frameworks.diskimages", key: "auto-open-rw-root", type: "bool", value: "true" },
    { domain: "com.apple.finder", key: "OpenWindowForNewRemovableDisk", type: "bool", value: "true" },
    # Global
    { domain: "com.apple.menuextra.clock", key: "DateFormat", type: "string", value: "EEE MMM d HH:mm" },
    { domain: "NSGlobalDomain", key: "AppleICUForce12HourTime", type: "boolean", value: "false" },
    { domain: "NSGlobalDomain", key: "AppleMeasurementUnits", type: "string", value: "Centimeters" },
    { domain: "NSGlobalDomain", key: "AppleMetricUnits", type: "boolean", value: "true" },
    { domain: "NSGlobalDomain", key: "AppleLocale", type: "string", value: "en_US@currency=USD" },
    { domain: "NSGlobalDomain", key: "AppleTemperatureUnit", type: "string", value: "Celsius" },
    { domain: "NSGlobalDomain", key: "NSAutomaticCapitalizationEnabled", type: "bool", value: "false" },
    { domain: "NSGlobalDomain", key: "NSAutomaticSpellingCorrectionEnabled", type: "bool", value: "false" },
    { domain: "NSGlobalDomain", key: "CheckSpellingWhileTyping", type: "bool", value: "false" },
    { domain: "NSGlobalDomain", key: "NSDocumentSaveNewDocumentsToCloud", type: "bool", value: "false" },
    { domain: "NSGlobalDomain", key: "NSNavPanelExpandedStateForSaveMode", type: "bool", value: "true" },
    { domain: "NSGlobalDomain", key: "NSNavPanelExpandedStateForSaveMode2", type: "bool", value: "true" },
    # SoftwareUpdate
    { domain: "com.apple.SoftwareUpdate", key: "AutomaticCheckEnabled", type: "bool", value: "true" },
    { domain: "com.apple.SoftwareUpdate", key: "AutomaticDownload", type: "bool", value: "true" },
    # Screensaver
    { domain: "com.apple.screensaver", key: "askForPassword", type: "int", value: "1" },
    { domain: "com.apple.screensaver", key: "askForPasswordDelay", type: "int", value: "0" },
    # DiskUtility
    { domain: "com.apple.DiskUtility", key: "SidebarShowAllDevices", type: "bool", value: "true" },
    # Other
    { domain: "com.apple.dashboard", key: "mcx-disabled", type: "bool", value: "true" },
    { domain: "com.apple.desktopservices", key: "DSDontWriteNetworkStores", type: "bool", value: "true" },
    { domain: "com.apple.Chrome", key: "AppleEnableSwipeNavigateWithScrolls", type: "bool", value: "false" },
    # Shortcut has type dict, ansible osx_defaults not support
    #    { domain: "com.apple.symbolichotkeys", key: "AppleSymbolicHotKeys", type: "dict", value:
    #      {
    #        # Screenshots
    #        28: { enabled: 0 }, # Save picture of screen as a file
    #        29: { enabled: 0 }, # Copy picture of screen to the clipboard
    #        30: { enabled: 0 }, # Save picture of selected area as a file
    #        31: { enabled: 0 }, # Copy picture of selected area to the clipboard
    #        184: { enabled: 0 }, # Screenshot and recording options
    #        # Spotlight
    #        64: { enabled: 0 }, # Show Spotlight search
    #      }
    #    },
  ]
  hot_keys: [
    { key: "28", dict: "
    <dict>
        <key>enabled</key><false/>
        <key>value</key><dict>
          <key>type</key><string>standard</string>
          <key>parameters</key>
          <array>
            <integer>51</integer>
            <integer>20</integer>
            <integer>1179648</integer>
          </array>
        </dict>
      </dict>
    " }, # Save picture of screen as a file
    { key: "29", dict: "
    <dict>
        <key>enabled</key><false/>
        <key>value</key><dict>
          <key>type</key><string>standard</string>
          <key>parameters</key>
          <array>
            <integer>51</integer>
            <integer>20</integer>
            <integer>1441792</integer>
          </array>
        </dict>
      </dict>
    " }, # Copy picture of screen to the clipboard
    { key: "30", dict: "
    <dict>
        <key>enabled</key><false/>
        <key>value</key><dict>
          <key>type</key><string>standard</string>
          <key>parameters</key>
          <array>
            <integer>52</integer>
            <integer>21</integer>
            <integer>1179648</integer>
          </array>
        </dict>
      </dict>
    " }, # Save picture of selected area as a file
    { key: "31", dict: "
    <dict>
        <key>enabled</key><false/>
        <key>value</key><dict>
          <key>type</key><string>standard</string>
          <key>parameters</key>
          <array>
            <integer>52</integer>
            <integer>21</integer>
            <integer>1441792</integer>
          </array>
        </dict>
      </dict>
    " }, # Copy picture of selected area to the clipboard
    { key: "184", dict: "
    <dict>
        <key>enabled</key><false/>
        <key>value</key><dict>
          <key>type</key><string>standard</string>
          <key>parameters</key>
          <array>
            <integer>53</integer>
            <integer>23</integer>
            <integer>1179648</integer>
          </array>
        </dict>
      </dict>
    " }, # Screenshot and recording options
    { key: "64", dict: "
    <dict>
        <key>enabled</key><false/>
        <key>value</key><dict>
          <key>type</key><string>standard</string>
          <key>parameters</key>
          <array>
            <integer>65535</integer>
            <integer>49</integer>
            <integer>1048576</integer>
          </array>
        </dict>
      </dict>
    " }, # Show Spotlight search
  ]
  man_page:
    key: [
      "com.apple.Terminal - Search man Page Index in Terminal - searchManPages",
      "com.apple.Terminal - Open man Page in Terminal - openManPage"
    ]
    dict: "
    <dict>
        <key>enabled_context_menu</key><integer>0</integer>
        <key>enabled_services_menu</key><integer>0</integer>
        <key>presentation_modes</key><dict>
           <key>ContextMenu</key><integer>0</integer>
           <key>ServicesMenu</key><integer>0</integer>
         </dict>
      </dict>
    "
  os_timezone: "Asia/Ho_Chi_Minh"
  computer_name: "hackintosh"
