---
- hosts: local

  vars_files:
    - config.yml

  tasks:
    - name: Install homebrew family
      include_tasks: tasks/homebrew.yml

    - name: Install application on mac app store
      include_tasks: tasks/mac_app_store.yml

    - name: Post-Install osx
      include_tasks: tasks/post_install.yml
