---
- name: Install homebrew package
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: force
    state: latest
  loop: "{{ brew_packages }}"

- name: Install homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_taps }}"

- name: Install homebrew application
  homebrew_cask:
    name: "{{ item }}"
    state: latest
    greedy: true
    install_options: quiet
  with_items: "{{ brew_apps }}"
