---
- name: Set the timezone to {{ post_install.os_timezone }}
  become: true
  shell: "systemsetup -settimezone '{{ post_install.os_timezone }}'"

- name: Set computer name {{ computer_name }}
  become: true
  shell: "scutil --set ComputerName {{ post_install.computer_name }}"

- name: Set localhost name {{ computer_name }}
  become: true
  shell: "scutil --set LocalHostName {{ post_install.computer_name }}"

- name: Setup macOS defaults
  become: "{{ item.global | default(false) }}"
  osx_defaults:
    array_add: "{{ item.add | default(false) }}"
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  when: item.enable | default(true)
  with_items: "{{ post_install.defaults }}"
  loop_control:
    label: "{{ item.description | default( item.domain + '.' + item.key) }} = {{ item.value }}"

- name: Setup macOS hot keys
  shell: "defaults write com.apple.symbolichotkeys.plist AppleSymbolicHotKeys -dict-add {{ item.key }} '{{ item.dict }}'"
  with_items: "{{ post_install.hot_keys }}"

- name: Disable Terminal - man Page
  shell: defaults write pbs NSServicesStatus -dict-add '{{ item }}' '{{ post_install.man_page.dict }}'
  with_items: "{{ post_install.man_page.key }}"

- name: Killall Dock
  shell: killall Dock
  ignore_errors: yes

- name: Killall Finder
  shell: killall Finder
  ignore_errors: yes



